name: s-git CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: |
        mkdir ci_build
        cd ci_build
        cmake ..
    - name: make
      run: make
      working-directory: ./ci_build
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: test
      run: python ./test/test.py s-git
